/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JniTest1 */

#ifndef _Included_jni_JniTest1
#define _Included_jni_JniTest1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JniTest1
 * Method:    getStrFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_JniTest1_getStrFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
